context:
  name: pgadmin4-python
  version: "9.6"
  python_min: "3.9"
  yarn_version: "3.8.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v${{ version }}/source/pgadmin4-${{ version }}.tar.gz
    sha256: 14cc35568bc9c9b797bd064507157bee7e57b2e3771e3b72cacce8bbb6664877
    patches:
      - patch-package.json.patch

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - pgadmin4 = pgadmin4.pgAdmin4:main
      - pgadmin4-cli = pgadmin4.setup:main

requirements:
  host:
    - Flask 3.1.*
    - Flask-Babel 4.0.*
    - Flask-Compress 1.*
    - Flask-Login 0.*
    - Flask-Mail 0.*
    - Flask-Migrate 4.*
    - Flask-Paranoid 0.*
    - Flask-Security-Too 5.4.*
    - Flask-SocketIO 5.5.*
    - Flask-SQLAlchemy 3.1.*
    - Flask-WTF 1.2.*
    - git
    - jinja2
    - jsonformatter =0.3.4
    - hatchling >=1.10
    - keyring 25.*
    - krb5
    - libgravatar
    - nodejs
    - pip
    - python-build
    - python-dateutil
    - python ${{ python_min }}.*
    - setuptools
    - sphinx
    - sphinxcontrib-youtube
    - Werkzeug 3.1.*
    - yarn ==${{ yarn_version }}
  run:
    - authlib 1.6.*
    - azure-identity ==1.23.0
    - azure-mgmt-rdbms ==10.1.0
    - azure-mgmt-resource ==24.0.0
    - azure-mgmt-subscription ==3.1.1
    - bcrypt 4.3.*
    - boto3 1.39.*
    - cryptography 45.0.*
    - Flask 3.1.*
    - Flask-Babel 4.0.*
    - Flask-Compress 1.*
    - Flask-Login 0.*
    - Flask-Mail 0.*
    - Flask-Migrate 4.*
    - Flask-Paranoid 0.*
    - Flask-Security-Too 5.4.*
    - Flask-SocketIO 5.5.*
    - Flask-SQLAlchemy 3.1.*
    - Flask-WTF 1.2.*
    - google-api-python-client 2.*
    - google-auth-oauthlib ==1.2.2
    - jsonformatter =0.3.4
    - keyring 25.*
    - ldap3 2.*
    - libgravatar 1.0.*
    - passlib 1.*
    - psutil 7.0.*
    - psycopg >=3.0.0,<3.3.0
    - psycopg-c >=3.0.0,<3.3.0
    - pytz 2025.*
    - pyotp 2.*
    - python >=${{ python_min }}
    - python-gssapi 1.9.*
    - qrcode 8.*
    - setuptools 75.*
    - SQLAlchemy 2.*
    - sqlparse 0.*
    - sshtunnel 0.*
    - typer 0.16.*
    - urllib3 1.26.*
    - user-agents ==2.2.0
    - wtforms 3.1.*

tests:
  - python:
      imports:
        - pgadmin4
      python_version: ${{ python_min }}.*
      pip_check: true
  - package_contents:
      files:
        - ${{ "Library/" if not unix else "" }}share/pgadmin4/docs/html/*
        - ${{ "Library/" if not unix else "" }}share/pgadmin4/docs/html/release_notes_${{ version | replace(".", "_") }}.html
      site_packages:
        - pgadmin4.pgadmin
  - script: |
      cd testing
      python run_entry_point_pgadmin4.py
    requirements: {run: ["python ${{ python_min }}.*"]}
    files: {recipe: [testing/]}
  - script: |
      cd testing
      python run_simple_pgadmin4.py
    requirements: {run: ["python ${{ python_min }}.*"]}
    files: {recipe: [testing/]}
  - script: |
      cd testing
      python run_simple_setup.py
    requirements: {run: ["python ${{ python_min }}.*"]}
    files: {recipe: [testing/]}
  - script: |
      cd testing
      python run_complex_tests.py
    requirements: {run: [postgresql 17.*, "python ${{ python_min }}.*"]}
    files: {source: [tests.tar, web/regression/], recipe: [testing/]}
  - script: |
      cd testing
      python run_complex_tests.py
    requirements: {run: [postgresql 16.*, "python ${{ python_min }}.*"]}
    files: {source: [tests.tar, web/regression/], recipe: [testing/]}
  - script: |
      cd testing
      python run_complex_tests.py
    requirements: {run: [postgresql 15.*, "python ${{ python_min }}.*"]}
    files: {source: [tests.tar, web/regression/], recipe: [testing/]}
  - script: |
      cd testing
      python run_complex_tests.py
    requirements: {run: [postgresql 14.*, "python ${{ python_min }}.*"]}
    files: {source: [tests.tar, web/regression/], recipe: [testing/]}

  # This seems incompatible with psycopg
  # - script: PY_VER=${{ python_min }} ./test.sh
  #   requirements: { run: [postgresql 13.*, "python ${{ python_min }}.*", typing_extensions 4.7.*] }
  #   files: { source: [web/regression/], recipe: [test.sh, testing/] }

about:
  homepage: https://github.com/pgadmin-org/pgadmin4
  summary: 'pgAdmin 4 is a rewrite of the popular pgAdmin3 management tool for the PostgreSQL'
  description: |
    pgAdmin is the most popular and feature rich Open Source administration and
    development platform for PostgreSQL, the most advanced Open Source database in the world.
  license: PostgreSQL
  license_file:
    - LICENSE
  documentation: https://www.pgadmin.org/
  repository: https://github.com/pgadmin-org/pgadmin4

extra:
  recipe-maintainers:
    - MementoRC
